import { decide, undoDecision, expireUndo } from "./restocks";
import { restockSnapshot } from "../lib/restockUndo";

// In-memory handler harness: snapshots are generated by decide, never supplied by the caller.
type Row = Record<string, any>;
const handler = (fn: unknown) =>
  (fn as { _handler: (ctx: any, args: any) => Promise<any> })._handler;
function harness() {
  let serial = 0;
  const rows = new Map<string, Row>([
    ["user", { _id: "user", clerkId: "clerk" }],
    ["house", { _id: "house", activeListId: "list" }],
    ["list", { _id: "list", householdId: "house", isArchived: false }],
    [
      "product",
      {
        _id: "product",
        householdId: "house",
        displayName: "Milk",
        normalizedName: "milk",
        status: "active",
        cadenceDays: 7,
        reviewAfter: 2,
        purchaseObservationCount: 1,
        createdAt: 1,
        updatedAt: 1,
      },
    ],
  ]);
  let signedIn = true,
    member = true;
  const ctx = {
    auth: {
      getUserIdentity: async () => (signedIn ? { subject: "clerk" } : null),
    },
    scheduler: { runAfter: jest.fn(async () => "scheduled") },
    db: {
      get: async (id: string) => rows.get(id) ?? null,
      insert: async (table: string, fields: Row) => {
        const id = `${table}_${++serial}`;
        rows.set(id, { ...fields, _id: id, _creationTime: 1 });
        return id;
      },
      patch: jest.fn(async (id: string, fields: Row) => {
        rows.set(id, { ...rows.get(id), ...fields });
      }),
      delete: jest.fn(async (id: string) => {
        rows.delete(id);
      }),
      query: (table: string) => ({
        withIndex: (_name: string, build: (q: any) => any) => {
          const filters: [string, unknown][] = [];
          const q = {
            eq: (field: string, value: unknown) => {
              filters.push([field, value]);
              return q;
            },
          };
          build(q);
          const found = () =>
            table === "users"
              ? [rows.get("user")]
              : table === "householdMembers"
                ? member
                  ? [{ userId: "user", householdId: "house" }]
                  : []
                : [...rows.values()].filter(
                    (row) =>
                      row._id.startsWith(`${table}_`) &&
                      filters.every(([key, value]) => row[key] === value),
                  );
          return {
            unique: async () => found()[0] ?? null,
            collect: async () => found(),
          };
        },
      }),
    },
  };
  return {
    ctx,
    rows,
    signOut: () => {
      signedIn = false;
    },
    leave: () => {
      member = false;
    },
    choose: (decision = "add") =>
      handler(decide)(ctx, {
        householdProductId: "product",
        decision,
        operationId: "op",
        expectedActiveListId: "list",
        enableUndo: true,
      }),
  };
}

describe("safe restock Undo", () => {
  it("restores timing and removes only its own untouched new item", async () => {
    const h = harness(),
      original = h.rows.get("product")!;
    const result = await h.choose();
    expect(result.undoId).toBeDefined();
    expect(h.ctx.scheduler.runAfter).toHaveBeenCalledWith(
      300000,
      expect.anything(),
      { undoId: result.undoId },
    );
    expect(
      await handler(undoDecision)(h.ctx, { undoId: result.undoId }),
    ).toEqual({ undone: true, productId: "product" });
    expect(h.rows.has(result.itemId)).toBe(false);
    expect(h.rows.get("product")).toMatchObject({
      cadenceDays: original.cadenceDays,
      reviewAfter: original.reviewAfter,
      recentOperationIds: ["op"],
    });
    h.ctx.db.patch.mockClear();
    h.ctx.db.delete.mockClear();
    expect(
      await handler(undoDecision)(h.ctx, { undoId: result.undoId }),
    ).toEqual({ undone: true, productId: "product" });
    expect(h.ctx.db.patch).not.toHaveBeenCalled();
    expect(h.ctx.db.delete).not.toHaveBeenCalled();
    const duplicate = await h.choose();
    expect(duplicate).toMatchObject({ applied: false });
    expect(duplicate.undoId).toBeUndefined();
    expect(
      [...h.rows.keys()].filter((id) => id.startsWith("items_")),
    ).toHaveLength(0);
  });
  it.each(["still_have_some", "not_this_time"])(
    "restores the reminder after %s",
    async (decision) => {
      const h = harness();
      const result = await h.choose(decision);
      await handler(undoDecision)(h.ctx, { undoId: result.undoId });
      expect(h.rows.get("product")).toMatchObject({
        cadenceDays: 7,
        reviewAfter: 2,
      });
    },
  );
  it("does not delete a pre-existing manually added product", async () => {
    const h = harness();
    h.rows.set("items_existing", {
      _id: "items_existing",
      listId: "list",
      name: "milk",
      isCompleted: false,
    });
    const result = await h.choose();
    expect(result.itemId).toBe("items_existing");
    await handler(undoDecision)(h.ctx, { undoId: result.undoId });
    expect(h.rows.has("items_existing")).toBe(true);
  });
  it.each([
    "edited item",
    "purchased item",
    "changed product",
    "changed list",
    "archived list",
  ])("refuses Undo after %s", async (reason) => {
    const h = harness();
    const result = await h.choose();
    if (reason === "edited item") h.rows.get(result.itemId)!.quantity = 9;
    if (reason === "purchased item")
      h.rows.get(result.itemId)!.isCompleted = true;
    if (reason === "changed product") h.rows.get("product")!.cadenceDays = 30;
    if (reason === "changed list") h.rows.get("house")!.activeListId = "other";
    if (reason === "archived list") h.rows.get("list")!.isArchived = true;
    h.ctx.db.patch.mockClear();
    expect(
      await handler(undoDecision)(h.ctx, { undoId: result.undoId }),
    ).toMatchObject({ undone: false, reason: "changed" });
    expect(h.rows.has(result.itemId)).toBe(true);
    expect(h.ctx.db.patch).not.toHaveBeenCalled();
  });
  it("requires authentication, membership and the original actor", async () => {
    const h = harness();
    const result = await h.choose();
    h.rows.get(result.undoId)!.userId = "someone_else";
    await expect(
      handler(undoDecision)(h.ctx, { undoId: result.undoId }),
    ).rejects.toThrow("another member");
    h.leave();
    await expect(
      handler(undoDecision)(h.ctx, { undoId: result.undoId }),
    ).rejects.toThrow("access");
    h.signOut();
    await expect(
      handler(undoDecision)(h.ctx, { undoId: result.undoId }),
    ).rejects.toThrow("authenticated");
  });
  it("expires without changing products or list items", async () => {
    const h = harness();
    const result = await h.choose();
    h.rows.get(result.undoId)!.expiresAt = 0;
    expect(
      await handler(undoDecision)(h.ctx, { undoId: result.undoId }),
    ).toMatchObject({ reason: "expired" });
    await handler(expireUndo)(h.ctx, { undoId: result.undoId });
    expect(h.rows.has(result.undoId)).toBe(false);
    expect(h.rows.has(result.itemId)).toBe(true);
  });
  it("returns the same live receipt for a retried operation", async () => {
    const h = harness();
    const first = await h.choose();
    const second = await h.choose();
    expect(second.undoId).toBe(first.undoId);
    expect(second.applied).toBe(false);
  });
  it("compares snapshots independently of property order and absent optional fields", () => {
    expect(restockSnapshot({ a: 1, b: undefined })).toBe(
      restockSnapshot({ a: 1 }),
    );
    expect(restockSnapshot({ a: 1, b: 2 })).toBe(
      restockSnapshot({ b: 2, a: 1 }),
    );
  });
});
